### ISSUE TITLE
default macOS run or serve command is not using my GPU on macOS with podman

### ISSUE THREAD

**Issue by benoitf** [containers/ramalama#857]
when running the command without my podman machine running
`ramalama serve huggingface://bartowski/granite-3.1-8b-instruct-GGUF/granite-3.1-8b-instruct-Q4_K_M.gguf`

if I query the model

```bash
curl --silent --location 'http://localhost:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
  "messages": [
    {
      "content": "What is 1+2 ?",
      "role": "user"
    }
  ]
}' | jq .choices
[
  {
    "finish_reason": "stop",
    "index": 0,
    "message": {
      "content": "1 + 2 equals $\\boxed{3}$ .",
      "tool_calls": null,
      "role": "assistant"
    }
  }
]
```

I can see my GPU is being used

but when running ramalama and with a podman machine (libkrun enabled)

krunkit is using all the CPU and my GPU is not used

I also try with `--device /dev/dri` but same result

![Image](https://github.com/user-attachments/assets/0409f0be-d704-44e1-8f8b-72e5acb06c44)

using AI Lab images it's using my GPU

**Comment by bmahabirbu** [comment]
Hi @benoitf I was checking this out! It works for me if im inside the VM with libkrun support (with ramalama installed inside the vm). 

If I use podman desktop and enable the vm (with libkrun) where podman cli is shared with the host terminal it will run but its not using the gpu. This is interesting because this should not work! When I use the vm with hyperv it wont run at all! Which is what I expected.

Looking at the code in common.py theres a check that passes the case if podman is being run with libkrun support but later in the process the code looks for /dev/dri path on mac natively which is a bug and it wont pass the gpu.

So I imagine to fix this ramalama should ignore looking for dev/dri on macos host and should automatically pass the /dev/dri path to the podman run/serve command. 

The reason why AI lab works is that the model serve container is being hosted inside the VM (same as if ramalama was installed inside the VM)

**Comment by rhatdan** [comment]
Please open a PR to fix this, and we can get another release out.

**Comment by ericcurtin** [comment]
> Hi [@benoitf](https://github.com/benoitf) I was checking this out! It works for me if im inside the VM with libkrun support (with ramalama installed inside the vm).
> 
> If I use podman desktop and enable the vm (with libkrun) where podman cli is shared with the host terminal it will run but its not using the gpu. This is interesting because this should not work! When I use the vm with hyperv it wont run at all! Which is what I expected.
> 
> Looking at the code in common.py theres a check that passes the case if podman is being run with libkrun support but later in the process the code looks for /dev/dri path on mac natively which is a bug and it wont pass the gpu.

/dev/dri sharing works fine on my machine at least, but there's no `-ngl 999` passed which I think is the issue.

```
$ bin/ramalama --dryrun run deepseek
podman run --rm -i --label ai.ramalama --name ramalama_L3v8lUUSQM --env=HOME=/tmp --init --security-opt=label=disable --cap-drop=all --security-opt=no-new-privileges --label ai.ramalama.model=ollama://deepseek-r1 --label ai.ramalama.engine=podman --label ai.ramalama.runtime=llama.cpp --label ai.ramalama.command=run --pull=newer -t --device /dev/dri --network none --mount=type=image,src=deepseek-r1,destination=/mnt/models,subpath=/models quay.io/ramalama/ramalama:latest llama-run -c 2048 --temp 0.8 /mnt/models/model.file
```

If we are on macOS (darwin) and podman (!= "docker"), /dev/dri should share just fine:

```
ramalama/model.py
214:            if (sys.platform == "darwin" and os.path.basename(args.engine) != "docker") or os.path.exists("/dev/dri"):
215:                conman_args += ["--device", "/dev/dri"]
```

it should be possible to get this working for accelerated docker on macOS also. No-one has put in the effort to check if docker is using krunkit yet.

> 
> So I imagine to fix this ramalama should ignore looking for dev/dri on macos host and should automatically pass the /dev/dri path to the podman run/serve command.
> 
> The reason why AI lab works is that the model serve container is being hosted inside the VM (same as if ramalama was installed inside the VM)

**Comment by bmahabirbu** [comment]
Ah gotcha that makes sense thanks Eric ya beat me to it!
