### ISSUE TITLE
Bug: could not select device driver "cdi" with capabilities: []

### ISSUE THREAD

**Issue by edmcman** [containers/ramalama#940]
I just tried ramalama for the first time by running `ramalama run ollama://tinyllama:latest`.

Here is the output:
```
 99% |████████████████████████████████████████ |  608.07 MB/ 608.16 MB   2.67 MB/s        0sUnable to find image 'quay.io/ramalama/cuda:latest' locally
latest: Pulling from ramalama/cuda
cc296d75b612: Pull complete 
723f563db35e: Pull complete 
09f0cdc6533e: Pull complete 
20a24fc15565: Pull complete 
9f5ffecfa071: Pull complete 
730406db7775: Pull complete 
79ee6520805c: Pull complete 
fef8f744dcbe: Pull complete 
6e93bc0ba6c4: Pull complete 
4a8824a37baa: Pull complete 
789e462ed2b1: Pull complete 
b736dac1f07a: Pull complete 
Digest: sha256:505cbde70808e1e465cef977216639f74445db6509526270540139acc12b2797
Status: Downloaded newer image for quay.io/ramalama/cuda:latest
docker: Error response from daemon: could not select device driver "cdi" with capabilities: []

Run 'docker run --help' for more information
```

Very minor: There should probably be a newline between downloading the model and running the docker container, e.g., "0s\nUnable..." instead of "0sUnable".

More problematic is the `cdi` error.

<details>
<summary>Output of `ramalama info`</summary>

```
{
    "Engine": {
        "Info": {
            "Architecture": "x86_64",
            "BridgeNfIp6tables": false,
            "BridgeNfIptables": false,
            "CDISpecDirs": [],
            "CPUSet": true,
            "CPUShares": true,
            "CgroupDriver": "systemd",
            "CgroupVersion": "2",
            "ClientInfo": {
                "Arch": "amd64",
                "BuildTime": "Wed Feb 19 22:10:30 2025",
                "Context": "default",
                "Debug": false,
                "GitCommit": "f9ced58",
                "GoVersion": "go1.23.6",
                "Os": "linux",
                "Platform": {
                    "Name": "Docker Engine - Community"
                },
                "Plugins": [
                    {
                        "Name": "buildx",
                        "Path": "/usr/libexec/docker/cli-plugins/docker-buildx",
                        "SchemaVersion": "0.1.0",
                        "ShortDescription": "Docker Buildx",
                        "Vendor": "Docker Inc.",
                        "Version": "v0.21.0"
                    },
                    {
                        "Name": "compose",
                        "Path": "/usr/libexec/docker/cli-plugins/docker-compose",
                        "SchemaVersion": "0.1.0",
                        "ShortDescription": "Docker Compose",
                        "Vendor": "Docker Inc.",
                        "Version": "v2.33.0"
                    }
                ],
                "Version": "28.0.0",
                "Warnings": null
            },
            "Containerd": {
                "Address": "/run/containerd/containerd.sock",
                "Namespaces": {
                    "Containers": "moby",
                    "Plugins": "plugins.moby"
                }
            },
            "ContainerdCommit": {
                "Expected": "bcc810d6b9066471b0b6fa75f557a15a1cbf31bb",
                "ID": "bcc810d6b9066471b0b6fa75f557a15a1cbf31bb"
            },
            "Containers": 23,
            "ContainersPaused": 0,
            "ContainersRunning": 0,
            "ContainersStopped": 23,
            "CpuCfsPeriod": true,
            "CpuCfsQuota": true,
            "Debug": false,
            "DefaultRuntime": "runc",
            "DockerRootDir": "/var/lib/docker",
            "Driver": "overlay2",
            "DriverStatus": [
                [
                    "Backing Filesystem",
                    "extfs"
                ],
                [
                    "Supports d_type",
                    "true"
                ],
                [
                    "Using metacopy",
                    "false"
                ],
                [
                    "Native Overlay Diff",
                    "true"
                ],
                [
                    "userxattr",
                    "false"
                ]
            ],
            "ExperimentalBuild": false,
            "GenericResources": null,
            "HttpProxy": "",
            "HttpsProxy": "",
            "ID": "612ff3e0-416b-4750-ab55-5ee99532fe83",
            "IPv4Forwarding": true,
            "Images": 69,
            "IndexServerAddress": "https://index.docker.io/v1/",
            "InitBinary": "docker-init",
            "InitCommit": {
                "Expected": "de40ad0",
                "ID": "de40ad0"
            },
            "Isolation": "",
            "KernelVersion": "6.8.0-51-generic",
            "Labels": [],
            "LiveRestoreEnabled": false,
            "LoggingDriver": "json-file",
            "MemTotal": 101080039424,
            "MemoryLimit": true,
            "NCPU": 32,
            "NEventsListener": 0,
            "NFd": 22,
            "NGoroutines": 41,
            "Name": "banana",
            "NoProxy": "",
            "OSType": "linux",
            "OSVersion": "22.04",
            "OomKillDisable": false,
            "OperatingSystem": "Ubuntu 22.04.5 LTS",
            "PidsLimit": true,
            "Plugins": {
                "Authorization": null,
                "Log": [
                    "awslogs",
                    "fluentd",
                    "gcplogs",
                    "gelf",
                    "journald",
                    "json-file",
                    "local",
                    "splunk",
                    "syslog"
                ],
                "Network": [
                    "bridge",
                    "host",
                    "ipvlan",
                    "macvlan",
                    "null",
                    "overlay"
                ],
                "Volume": [
                    "local"
                ]
            },
            "RegistryConfig": {
                "IndexConfigs": {
                    "docker.io": {
                        "Mirrors": [],
                        "Name": "docker.io",
                        "Official": true,
                        "Secure": true
                    }
                },
                "InsecureRegistryCIDRs": [
                    "::1/128",
                    "127.0.0.0/8"
                ],
                "Mirrors": null
            },
            "RuncCommit": {
                "Expected": "v1.2.4-0-g6c52b3f",
                "ID": "v1.2.4-0-g6c52b3f"
            },
            "Runtimes": {
                "io.containerd.runc.v2": {
                    "path": "runc",
                    "status": {
                        "org.opencontainers.runtime-spec.features": "{\"ociVersionMin\":\"1.0.0\",\"ociVersionMax\":\"1.2.0\",\"hooks\":[\"prestart\",\"createRuntime\",\"createContainer\",\"startContainer\",\"poststart\",\"poststop\"],\"mountOptions\":[\"async\",\"atime\",\"bind\",\"defaults\",\"dev\",\"diratime\",\"dirsync\",\"exec\",\"iversion\",\"lazytime\",\"loud\",\"mand\",\"noatime\",\"nodev\",\"nodiratime\",\"noexec\",\"noiversion\",\"nolazytime\",\"nomand\",\"norelatime\",\"nostrictatime\",\"nosuid\",\"nosymfollow\",\"private\",\"ratime\",\"rbind\",\"rdev\",\"rdiratime\",\"relatime\",\"remount\",\"rexec\",\"rnoatime\",\"rnodev\",\"rnodiratime\",\"rnoexec\",\"rnorelatime\",\"rnostrictatime\",\"rnosuid\",\"rnosymfollow\",\"ro\",\"rprivate\",\"rrelatime\",\"rro\",\"rrw\",\"rshared\",\"rslave\",\"rstrictatime\",\"rsuid\",\"rsymfollow\",\"runbindable\",\"rw\",\"shared\",\"silent\",\"slave\",\"strictatime\",\"suid\",\"symfollow\",\"sync\",\"tmpcopyup\",\"unbindable\"],\"linux\":{\"namespaces\":[\"cgroup\",\"ipc\",\"mount\",\"network\",\"pid\",\"time\",\"user\",\"uts\"],\"capabilities\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_DAC_READ_SEARCH\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_SETGID\",\"CAP_SETUID\",\"CAP_SETPCAP\",\"CAP_LINUX_IMMUTABLE\",\"CAP_NET_BIND_SERVICE\",\"CAP_NET_BROADCAST\",\"CAP_NET_ADMIN\",\"CAP_NET_RAW\",\"CAP_IPC_LOCK\",\"CAP_IPC_OWNER\",\"CAP_SYS_MODULE\",\"CAP_SYS_RAWIO\",\"CAP_SYS_CHROOT\",\"CAP_SYS_PTRACE\",\"CAP_SYS_PACCT\",\"CAP_SYS_ADMIN\",\"CAP_SYS_BOOT\",\"CAP_SYS_NICE\",\"CAP_SYS_RESOURCE\",\"CAP_SYS_TIME\",\"CAP_SYS_TTY_CONFIG\",\"CAP_MKNOD\",\"CAP_LEASE\",\"CAP_AUDIT_WRITE\",\"CAP_AUDIT_CONTROL\",\"CAP_SETFCAP\",\"CAP_MAC_OVERRIDE\",\"CAP_MAC_ADMIN\",\"CAP_SYSLOG\",\"CAP_WAKE_ALARM\",\"CAP_BLOCK_SUSPEND\",\"CAP_AUDIT_READ\",\"CAP_PERFMON\",\"CAP_BPF\",\"CAP_CHECKPOINT_RESTORE\"],\"cgroup\":{\"v1\":true,\"v2\":true,\"systemd\":true,\"systemdUser\":true,\"rdma\":true},\"seccomp\":{\"enabled\":true,\"actions\":[\"SCMP_ACT_ALLOW\",\"SCMP_ACT_ERRNO\",\"SCMP_ACT_KILL\",\"SCMP_ACT_KILL_PROCESS\",\"SCMP_ACT_KILL_THREAD\",\"SCMP_ACT_LOG\",\"SCMP_ACT_NOTIFY\",\"SCMP_ACT_TRACE\",\"SCMP_ACT_TRAP\"],\"operators\":[\"SCMP_CMP_EQ\",\"SCMP_CMP_GE\",\"SCMP_CMP_GT\",\"SCMP_CMP_LE\",\"SCMP_CMP_LT\",\"SCMP_CMP_MASKED_EQ\",\"SCMP_CMP_NE\"],\"archs\":[\"SCMP_ARCH_AARCH64\",\"SCMP_ARCH_ARM\",\"SCMP_ARCH_MIPS\",\"SCMP_ARCH_MIPS64\",\"SCMP_ARCH_MIPS64N32\",\"SCMP_ARCH_MIPSEL\",\"SCMP_ARCH_MIPSEL64\",\"SCMP_ARCH_MIPSEL64N32\",\"SCMP_ARCH_PPC\",\"SCMP_ARCH_PPC64\",\"SCMP_ARCH_PPC64LE\",\"SCMP_ARCH_RISCV64\",\"SCMP_ARCH_S390\",\"SCMP_ARCH_S390X\",\"SCMP_ARCH_X32\",\"SCMP_ARCH_X86\",\"SCMP_ARCH_X86_64\"],\"knownFlags\":[\"SECCOMP_FILTER_FLAG_TSYNC\",\"SECCOMP_FILTER_FLAG_SPEC_ALLOW\",\"SECCOMP_FILTER_FLAG_LOG\"],\"supportedFlags\":[\"SECCOMP_FILTER_FLAG_TSYNC\",\"SECCOMP_FILTER_FLAG_SPEC_ALLOW\",\"SECCOMP_FILTER_FLAG_LOG\"]},\"apparmor\":{\"enabled\":true},\"selinux\":{\"enabled\":true},\"intelRdt\":{\"enabled\":true},\"mountExtensions\":{\"idmap\":{\"enabled\":true}}},\"annotations\":{\"io.github.seccomp.libseccomp.version\":\"2.5.3\",\"org.opencontainers.runc.checkpoint.enabled\":\"true\",\"org.opencontainers.runc.commit\":\"v1.2.4-0-g6c52b3f\",\"org.opencontainers.runc.version\":\"1.2.4\"},\"potentiallyUnsafeConfigAnnotations\":[\"bundle\",\"org.systemd.property.\",\"org.criu.config\"]}"
                    }
                },
                "nvidia": {
                    "path": "nvidia-container-runtime",
                    "status": {
                        "org.opencontainers.runtime-spec.features": "{\"ociVersionMin\":\"1.0.0\",\"ociVersionMax\":\"1.2.0\",\"hooks\":[\"prestart\",\"createRuntime\",\"createContainer\",\"startContainer\",\"poststart\",\"poststop\"],\"mountOptions\":[\"async\",\"atime\",\"bind\",\"defaults\",\"dev\",\"diratime\",\"dirsync\",\"exec\",\"iversion\",\"lazytime\",\"loud\",\"mand\",\"noatime\",\"nodev\",\"nodiratime\",\"noexec\",\"noiversion\",\"nolazytime\",\"nomand\",\"norelatime\",\"nostrictatime\",\"nosuid\",\"nosymfollow\",\"private\",\"ratime\",\"rbind\",\"rdev\",\"rdiratime\",\"relatime\",\"remount\",\"rexec\",\"rnoatime\",\"rnodev\",\"rnodiratime\",\"rnoexec\",\"rnorelatime\",\"rnostrictatime\",\"rnosuid\",\"rnosymfollow\",\"ro\",\"rprivate\",\"rrelatime\",\"rro\",\"rrw\",\"rshared\",\"rslave\",\"rstrictatime\",\"rsuid\",\"rsymfollow\",\"runbindable\",\"rw\",\"shared\",\"silent\",\"slave\",\"strictatime\",\"suid\",\"symfollow\",\"sync\",\"tmpcopyup\",\"unbindable\"],\"linux\":{\"namespaces\":[\"cgroup\",\"ipc\",\"mount\",\"network\",\"pid\",\"time\",\"user\",\"uts\"],\"capabilities\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_DAC_READ_SEARCH\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_SETGID\",\"CAP_SETUID\",\"CAP_SETPCAP\",\"CAP_LINUX_IMMUTABLE\",\"CAP_NET_BIND_SERVICE\",\"CAP_NET_BROADCAST\",\"CAP_NET_ADMIN\",\"CAP_NET_RAW\",\"CAP_IPC_LOCK\",\"CAP_IPC_OWNER\",\"CAP_SYS_MODULE\",\"CAP_SYS_RAWIO\",\"CAP_SYS_CHROOT\",\"CAP_SYS_PTRACE\",\"CAP_SYS_PACCT\",\"CAP_SYS_ADMIN\",\"CAP_SYS_BOOT\",\"CAP_SYS_NICE\",\"CAP_SYS_RESOURCE\",\"CAP_SYS_TIME\",\"CAP_SYS_TTY_CONFIG\",\"CAP_MKNOD\",\"CAP_LEASE\",\"CAP_AUDIT_WRITE\",\"CAP_AUDIT_CONTROL\",\"CAP_SETFCAP\",\"CAP_MAC_OVERRIDE\",\"CAP_MAC_ADMIN\",\"CAP_SYSLOG\",\"CAP_WAKE_ALARM\",\"CAP_BLOCK_SUSPEND\",\"CAP_AUDIT_READ\",\"CAP_PERFMON\",\"CAP_BPF\",\"CAP_CHECKPOINT_RESTORE\"],\"cgroup\":{\"v1\":true,\"v2\":true,\"systemd\":true,\"systemdUser\":true,\"rdma\":true},\"seccomp\":{\"enabled\":true,\"actions\":[\"SCMP_ACT_ALLOW\",\"SCMP_ACT_ERRNO\",\"SCMP_ACT_KILL\",\"SCMP_ACT_KILL_PROCESS\",\"SCMP_ACT_KILL_THREAD\",\"SCMP_ACT_LOG\",\"SCMP_ACT_NOTIFY\",\"SCMP_ACT_TRACE\",\"SCMP_ACT_TRAP\"],\"operators\":[\"SCMP_CMP_EQ\",\"SCMP_CMP_GE\",\"SCMP_CMP_GT\",\"SCMP_CMP_LE\",\"SCMP_CMP_LT\",\"SCMP_CMP_MASKED_EQ\",\"SCMP_CMP_NE\"],\"archs\":[\"SCMP_ARCH_AARCH64\",\"SCMP_ARCH_ARM\",\"SCMP_ARCH_MIPS\",\"SCMP_ARCH_MIPS64\",\"SCMP_ARCH_MIPS64N32\",\"SCMP_ARCH_MIPSEL\",\"SCMP_ARCH_MIPSEL64\",\"SCMP_ARCH_MIPSEL64N32\",\"SCMP_ARCH_PPC\",\"SCMP_ARCH_PPC64\",\"SCMP_ARCH_PPC64LE\",\"SCMP_ARCH_RISCV64\",\"SCMP_ARCH_S390\",\"SCMP_ARCH_S390X\",\"SCMP_ARCH_X32\",\"SCMP_ARCH_X86\",\"SCMP_ARCH_X86_64\"],\"knownFlags\":[\"SECCOMP_FILTER_FLAG_TSYNC\",\"SECCOMP_FILTER_FLAG_SPEC_ALLOW\",\"SECCOMP_FILTER_FLAG_LOG\"],\"supportedFlags\":[\"SECCOMP_FILTER_FLAG_TSYNC\",\"SECCOMP_FILTER_FLAG_SPEC_ALLOW\",\"SECCOMP_FILTER_FLAG_LOG\"]},\"apparmor\":{\"enabled\":true},\"selinux\":{\"enabled\":true},\"intelRdt\":{\"enabled\":true},\"mountExtensions\":{\"idmap\":{\"enabled\":true}}},\"annotations\":{\"io.github.seccomp.libseccomp.version\":\"2.5.3\",\"org.opencontainers.runc.checkpoint.enabled\":\"true\",\"org.opencontainers.runc.commit\":\"v1.2.4-0-g6c52b3f\",\"org.opencontainers.runc.version\":\"1.2.4\"},\"potentiallyUnsafeConfigAnnotations\":[\"bundle\",\"org.systemd.property.\",\"org.criu.config\"]}"
                    }
                },
                "runc": {
                    "path": "runc",
                    "status": {
                        "org.opencontainers.runtime-spec.features": "{\"ociVersionMin\":\"1.0.0\",\"ociVersionMax\":\"1.2.0\",\"hooks\":[\"prestart\",\"createRuntime\",\"createContainer\",\"startContainer\",\"poststart\",\"poststop\"],\"mountOptions\":[\"async\",\"atime\",\"bind\",\"defaults\",\"dev\",\"diratime\",\"dirsync\",\"exec\",\"iversion\",\"lazytime\",\"loud\",\"mand\",\"noatime\",\"nodev\",\"nodiratime\",\"noexec\",\"noiversion\",\"nolazytime\",\"nomand\",\"norelatime\",\"nostrictatime\",\"nosuid\",\"nosymfollow\",\"private\",\"ratime\",\"rbind\",\"rdev\",\"rdiratime\",\"relatime\",\"remount\",\"rexec\",\"rnoatime\",\"rnodev\",\"rnodiratime\",\"rnoexec\",\"rnorelatime\",\"rnostrictatime\",\"rnosuid\",\"rnosymfollow\",\"ro\",\"rprivate\",\"rrelatime\",\"rro\",\"rrw\",\"rshared\",\"rslave\",\"rstrictatime\",\"rsuid\",\"rsymfollow\",\"runbindable\",\"rw\",\"shared\",\"silent\",\"slave\",\"strictatime\",\"suid\",\"symfollow\",\"sync\",\"tmpcopyup\",\"unbindable\"],\"linux\":{\"namespaces\":[\"cgroup\",\"ipc\",\"mount\",\"network\",\"pid\",\"time\",\"user\",\"uts\"],\"capabilities\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_DAC_READ_SEARCH\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_SETGID\",\"CAP_SETUID\",\"CAP_SETPCAP\",\"CAP_LINUX_IMMUTABLE\",\"CAP_NET_BIND_SERVICE\",\"CAP_NET_BROADCAST\",\"CAP_NET_ADMIN\",\"CAP_NET_RAW\",\"CAP_IPC_LOCK\",\"CAP_IPC_OWNER\",\"CAP_SYS_MODULE\",\"CAP_SYS_RAWIO\",\"CAP_SYS_CHROOT\",\"CAP_SYS_PTRACE\",\"CAP_SYS_PACCT\",\"CAP_SYS_ADMIN\",\"CAP_SYS_BOOT\",\"CAP_SYS_NICE\",\"CAP_SYS_RESOURCE\",\"CAP_SYS_TIME\",\"CAP_SYS_TTY_CONFIG\",\"CAP_MKNOD\",\"CAP_LEASE\",\"CAP_AUDIT_WRITE\",\"CAP_AUDIT_CONTROL\",\"CAP_SETFCAP\",\"CAP_MAC_OVERRIDE\",\"CAP_MAC_ADMIN\",\"CAP_SYSLOG\",\"CAP_WAKE_ALARM\",\"CAP_BLOCK_SUSPEND\",\"CAP_AUDIT_READ\",\"CAP_PERFMON\",\"CAP_BPF\",\"CAP_CHECKPOINT_RESTORE\"],\"cgroup\":{\"v1\":true,\"v2\":true,\"systemd\":true,\"systemdUser\":true,\"rdma\":true},\"seccomp\":{\"enabled\":true,\"actions\":[\"SCMP_ACT_ALLOW\",\"SCMP_ACT_ERRNO\",\"SCMP_ACT_KILL\",\"SCMP_ACT_KILL_PROCESS\",\"SCMP_ACT_KILL_THREAD\",\"SCMP_ACT_LOG\",\"SCMP_ACT_NOTIFY\",\"SCMP_ACT_TRACE\",\"SCMP_ACT_TRAP\"],\"operators\":[\"SCMP_CMP_EQ\",\"SCMP_CMP_GE\",\"SCMP_CMP_GT\",\"SCMP_CMP_LE\",\"SCMP_CMP_LT\",\"SCMP_CMP_MASKED_EQ\",\"SCMP_CMP_NE\"],\"archs\":[\"SCMP_ARCH_AARCH64\",\"SCMP_ARCH_ARM\",\"SCMP_ARCH_MIPS\",\"SCMP_ARCH_MIPS64\",\"SCMP_ARCH_MIPS64N32\",\"SCMP_ARCH_MIPSEL\",\"SCMP_ARCH_MIPSEL64\",\"SCMP_ARCH_MIPSEL64N32\",\"SCMP_ARCH_PPC\",\"SCMP_ARCH_PPC64\",\"SCMP_ARCH_PPC64LE\",\"SCMP_ARCH_RISCV64\",\"SCMP_ARCH_S390\",\"SCMP_ARCH_S390X\",\"SCMP_ARCH_X32\",\"SCMP_ARCH_X86\",\"SCMP_ARCH_X86_64\"],\"knownFlags\":[\"SECCOMP_FILTER_FLAG_TSYNC\",\"SECCOMP_FILTER_FLAG_SPEC_ALLOW\",\"SECCOMP_FILTER_FLAG_LOG\"],\"supportedFlags\":[\"SECCOMP_FILTER_FLAG_TSYNC\",\"SECCOMP_FILTER_FLAG_SPEC_ALLOW\",\"SECCOMP_FILTER_FLAG_LOG\"]},\"apparmor\":{\"enabled\":true},\"selinux\":{\"enabled\":true},\"intelRdt\":{\"enabled\":true},\"mountExtensions\":{\"idmap\":{\"enabled\":true}}},\"annotations\":{\"io.github.seccomp.libseccomp.version\":\"2.5.3\",\"org.opencontainers.runc.checkpoint.enabled\":\"true\",\"org.opencontainers.runc.commit\":\"v1.2.4-0-g6c52b3f\",\"org.opencontainers.runc.version\":\"1.2.4\"},\"potentiallyUnsafeConfigAnnotations\":[\"bundle\",\"org.systemd.property.\",\"org.criu.config\"]}"
                    }
                }
            },
            "SecurityOptions": [
                "name=apparmor",
                "name=seccomp,profile=builtin",
                "name=cgroupns"
            ],
            "ServerVersion": "28.0.0",
            "SwapLimit": true,
            "Swarm": {
                "ControlAvailable": false,
                "Error": "",
                "LocalNodeState": "inactive",
                "NodeAddr": "",
                "NodeID": "",
                "RemoteManagers": null
            },
            "SystemTime": "2025-03-11T09:59:52.759200568-04:00",
            "Warnings": null
        },
        "Name": "docker"
    },
    "GPUs": {
        "Detected GPUs": [
            {
                "Details": "GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU (UUID: GPU-02187fd8-22a1-3f71-cd52-22af54f42481)",
                "Env": "CUDA_VISIBLE_DEVICES",
                "GPU": "NVIDIA GPU",
                "VRAM": "8188 MiB"
            }
        ],
        "INFO": [
            {
                "INFO": "No AMD GPU detected or drivers missing.",
                "Vendor": "AMD"
            },
            {
                "INFO": "'NoneType' object is not iterable",
                "Vendor": "Intel"
            }
        ]
    },
    "Image": "quay.io/ramalama/ramalama",
    "Runtime": "llama.cpp",
    "Store": "/home/ed/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.6.3"
}
```

</details>

**Comment by rhatdan** [comment]
Could you try with Podman?  

Are you running with a non root docker client?

**Comment by edmcman** [comment]
> Could you try with Podman?

Will do

> Are you running with a non root docker client?

I'm not sure what you mean.  I was not running as root when I invoked ramalama.

**Comment by rhatdan** [comment]
Ok I will try this with Docker on my laptop with (nvidia gpu)

**Comment by edmcman** [comment]
FWIW, I have `nvidia-container-toolkit` installed, but I have never configured it for cdi.  Claude suggested I run this command: `sudo nvidia-ctk runtime configure --runtime=docker --set-as-default`

**Comment by edmcman** [comment]
I'll confirm when I get home, but I have used --gpus=all before
successfully.

**Comment by edmcman** [comment]
This fixed that issue, but now hit #944
